// SPDX-License-Identifier: Apache-2.0

package dotvisualizer

import java.io.{File, PrintWriter}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.Duration
import scala.concurrent.{blocking, Await, Future, TimeoutException}
import scala.sys.process._

class RenderSvg(dotProgram: String = "dot", dotTimeOut: Int = 7) {
  def render(fileName: String): Unit = {
    if (dotProgram != "none") {
      if (fileName.isEmpty) {
        println(s"Tried to call render program $dotProgram without a filename")
      } else if (!new File(fileName).exists()) {
        println(s"Tried to call render program $dotProgram on non existent file $fileName")
      } else {
        val dotProcessString = s"$dotProgram -Tsvg -O $fileName"
        val process = Process(dotProcessString).run()
        val processFuture = Future(blocking(process.exitValue()))
        try {
          Await.result(processFuture, Duration(dotTimeOut, "sec"))
        } catch {
          case _: TimeoutException =>
            println(s"Rendering timed out after $dotTimeOut seconds on $fileName with command $dotProcessString")
            println(s"You can try increasing with the --dot-timeout seconds flag")
            process.destroy()
            val printWriter = new PrintWriter(new File(fileName + ".svg"))
            printWriter.print(s"""
                                 |<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
                                 | "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
                                 |<!-- Generated by graphviz version 2.40.1 (20161225.0304)
                                 | -->
                                 |<!-- Title: TopLevel Pages: 1 -->
                                 |<svg width="351pt" height="44pt"
                                 | viewBox="0.00 0.00 351.26 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                 |<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
                                 |<title>TopLevel</title>
                                 |<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 347.2637,-40 347.2637,4 -4,4"/>
                                 |<!-- Sorry, Rendering timed out on this file, Use Back to return -->
                                 |<g id="node1" class="node">
                                 |<title>
                                 |Sorry, Rendering timed out on this file, Use Back to return.
                                 |You can try increasing the timeout with the --dot-timeout seconds flag
                                 |</title>
                                 |<polygon fill="none" stroke="#000000" points="343.3956,-36 -.1319,-36 -.1319,0 343.3956,0 343.3956,-36"/>
                                 |<text text-anchor="middle" x="171.6318" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Sorry, Rendering timed out on this file, Use Back to return</text>
                                 |</g>
                                 |</g>
                                 |</svg>
              """.stripMargin)
            printWriter.close()

        }
      }
    }
  }

}
